apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kvstore
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
      - name: kvstore
        image: kvstore:assignment
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-headless
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /redis-conf
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "hostpath"
      resources:
        requests:
          storage: 1Gi

--- 

####################### Service Configurations #######################

apiVersion: v1
kind: Service
metadata:
  name: kvstore-service 
spec:
  type: NodePort  
  selector:
    app: kvstore
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30000

---

apiVersion: v1
kind: Service  
metadata:
  name: redis-headless
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service 
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

---

####################### Redis Configuration File #######################

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  master.conf: |
    port 6379
    
  replica.conf: |
    port 6379 
    replicaof redis-0 6379